name: atma_kitchen_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_initicon: ^3.0.0+1
  flutter_riverpod: ^2.4.10
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  intl: ^0.19.0
  navigation_view: ^1.0.6
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
